Repository mattermost/mattermost-plugin-boards, pull requests merged in 2024-12, with the labels that each got.

#40 MM-61945: Able to add individual users to the boards
  server/services/store/sqlstore/board.go
Labels: 2: Dev Review, 2: QA Review

#41 Added linked and table renderer for markdown in comment
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/commentsList.test.tsx.snap
  webapp/src/components/cardDetail/comment.scss
  webapp/src/components/cardDetail/comment.tsx
  webapp/src/utils.ts
  webapp/src/webapp_globals.ts
Labels: 2: Dev Review, 2: QA Review

#36 [MM-61123] Add diagnostics data to the Support Packet
  go.mod
  go.sum
  server/api/statistics.go
  server/app/blocks_test.go
  server/app/boards.go
  server/app/boards_test.go
  server/app/statistics.go
  server/boards/boardsapp.go
  server/boards/boardsapp_test.go
  server/boards/support_packet.go
  server/integrationtests/pluginteststore.go
  server/model/board_statistics.go
  server/plugin.go
  server/server/server.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/cloud.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/boards.go
  server/services/telemetry/mocks/ServerIface.go
Labels: 4: Reviews Complete

#44 MM-62104 Fix board disappearing or move to default category when switching teams
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 2: Dev Review, 3: QA Review

#45 Update board version to 9.0.4
  plugin.json
  server/manifest.go
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review
