Repository mattermost/mattermost-plugin-boards, pull requests merged in 2025-01, with the labels that each got.

#47 Fix the comments link and markdown rendering issue
  webapp/src/components/cardDetail/comment.scss
  webapp/src/components/cardDetail/comment.tsx
  webapp/src/webapp_globals.ts
Labels: 2: Dev Review, 3: QA Review

#55 Improved ID validation
  Makefile
  server/app/category.go
  server/model/base.go
  server/model/base_test.go
  server/model/block.go
  server/model/board.go
  server/model/category.go
  server/model/category_test.go
  server/model/notification.go
  server/model/subscription.go
  server/services/store/sqlstore/category.go
  server/services/store/sqlstore/category_boards.go
  server/services/store/sqlstore/migrationstests/de_duplicate_category_boards_migration_test.go
Labels: 4: Reviews Complete

#56 Added Validation for block patch
  server/api/blocks.go
  server/app/blocks.go
  server/app/files.go
  server/app/files_test.go
  server/app/import.go
  server/model/base.go
  server/model/block.go
  server/model/block_test.go
Labels: 2: Dev Review, 3: QA Review

#57 Version update to 9.0.5 for plugin.json and client side
  plugin.json
  server/manifest.go
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#59 Added legacy ID check support
  server/model/base.go
  server/model/base_test.go
  server/model/block.go
  server/model/block_test.go
Labels: 4: Reviews Complete

#60 MM-61745 Update Boards Navigation to Use the New Desktop API
  webapp/package-lock.json
  webapp/package.json
  webapp/src/index.tsx
  webapp/src/types/index.d.ts
Labels: 2: Dev Review, 3: QA Review

#61 Updated board version to v9.1.0
  plugin.json
  server/manifest.go
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review, 3: QA Review
